version: '3.5'

services:
  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    image: ffmpeg-multitrack-controller:local
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - RECORDER_API_SECRET
      - RECORDINGS_PATH=/recordings/ffmpeg
      - JVB_COLIBRI2_URL
      - JVB_COLIBRI2_WS
      - LOG_LEVEL=info
    networks:
      meet.jitsi:
    volumes:
      - ${RECORDINGS_PATH:-./recordings}:/recordings:Z
    ports:
      # Expose only if you need host access; otherwise rely on internal Docker network.
      - "127.0.0.1:${RECORDER_API_PORT:-8288}:8080"

networks:
  meet.jitsi:
    external: true
