version: '3.5'

services:
  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    image: ffmpeg-multitrack-controller:local
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - RECORDER_API_SECRET
      - RECORDINGS_PATH=/recordings/ffmpeg
      - JVB_COLIBRI2_URL
      - JVB_COLIBRI2_WS
      - LOG_LEVEL=info
      # XMPP Client Mode
      - XMPP_JID
      - XMPP_PASSWORD
      - XMPP_HOST
      - XMPP_PORT
      # XMPP Component Mode
      - XMPP_COMPONENT_HOST
      - XMPP_COMPONENT_PORT
      - XMPP_COMPONENT_JID
      - XMPP_COMPONENT_SECRET
      - XMPP_DOMAIN
      - JVB_BRIDGE_MUC
      - COLIBRI2_SIMULATE
    volumes:
      - ./controller:/app
      - ${RECORDINGS_PATH:-./recordings}:/recordings:Z
    networks:
      meet.jitsi:
    ports:
      # Expose only if you need host access; otherwise rely on internal Docker network.
      - "127.0.0.1:${RECORDER_API_PORT:-8288}:8080"

networks:
  meet.jitsi:
    external:
      name: jitsi-multitrack-recording_meet.jitsi
